### PR TITLE
Upgrade to OCaml 4.08

### PR DESCRIPTION
**Pull request by glennsl**
Remaining issues:

- This builds, tests and benches fine, but has not otherwise been tested because the SDL2 bug prevents me from running it properly.

- Several dependencies have been updated to get constraints to solve. These constraints generally seem too narrow, either specifying a single version or a minor version. Relaxing this to a major version should be fine, as long as warnings-as-errors are turned off. [These dependencies](https://github.com/onivim/oni2/blob/601aaf9e742e045108fa2f96a871e99db366c69a/package.json#L228-L235) are mostly pinned to my own forks right now, but will be listed here when PRs have been submitted.

- This might be a good opportunity to look over the other pins, as they might no longer be needed. I removed the jsoo pins as the pinned patch was released as far back as in April.

(minor edit by __@bryphe__ - just adding a checklist of libs to bring in)
- [x] `reason-textmate`
- [x] `reason-libvim`
- [x] `isolinear`
- [x] `facebook/reason`
- [x] `CrossR/reasonFuzz`
- [x] `bryphe/reason-jsonrpc`

And another few PRs that need merging before this can be merged:
- [x] https://github.com/onivim/reason-textmate/pull/50
- [x] https://github.com/bryphe/reperf/pull/5
- [x] https://github.com/esy-ocaml/libffi/pull/3
- [x] https://github.com/revery-ui/reason-skia/pull/42

### CODE REVIEW

File: bench/lib/TokenizerBench.re [hunk 1]
```diff
@@ -17,17 +17,27 @@ let splitEverything = (_, _, _, _) => true;
...
 let tokenizeWithoutSplits = () => {
-  let _ = Tokenizer.tokenize(~f=splitNothing, giantString);
+  let _: list(Tokenizer.TextRun.t) =
+    Tokenizer.tokenize(
+      ~f=splitNothing,
+      ~endIndex=BufferLine.lengthSlow(giantString),
+      giantString,
+    );
   ();
 };
```
Comment (glennsl) [inline bench/lib/TokenizerBench.re]: These are actual partial application bugs prevented by the warning and type annotations. This code was nothing after `~endIndex` was added because this then resulted in a partial application.

You might want to double check the BufferLine benchmarks after fixing this.

File: src/Extensions/ExtHostClient.re [hunk 2]
```diff
@@ -175,7 +174,7 @@ let start =
     | ("MainThreadSCM", "$registerSourceControl", args) =>
       switch (args) {
       | [`Int(handle), `String(id), `String(label), rootUri] =>
-        let rootUri = Core.Uri.of_yojson(rootUri) |> Utility.Result.to_option;
+        let rootUri = Core.Uri.of_yojson(rootUri) |> Stdlib.Result.to_option;
```
Comment (glennsl) [inline src/Extensions/ExtHostClient.re]: Unfortunately it seems we have to add `Stdlib.` to every use of `Result`, because there is an `@opam/result` polyfill package used by lots of other packages which adds a `Result` module that'll otherwise override it.

**Comment by glennsl** [comment]
Alright, Oni2 now builds with 4.08! This should be ready to merge then.

I've also tried to get it to work with 4.09, but encounter a weird issue with a `reacon-cli` constraint that I don't understand where comes from. This is an issue with several packages I've tried to upgrade, so it's probably better to try to address those first. See https://github.com/onivim/editor-core-types/pull/1 and https://github.com/onivim/reason-textmate/pull/50

**Comment by glennsl** [comment]
Oh wait, I forgot to upgrade `facebook/reason`, which seems to be the actual cause of the problem. https://github.com/facebook/reason/pull/2457 seems to still be needed.

**Comment by glennsl** [comment]
It now compiles with HEAD of facebook/reason#master, but this broke reason-textmate and reperf, so the PRs for those ought to be merged first. But once that's done this should finally be ready to go!

**Comment by bryphe** [comment]
Thanks @glennsl ! I've published `reperf@1.5.0` with your changes.

Looking at `reason-textmate` now...

**Comment by glennsl** [comment]
Hmmm, linker error on macOS:

```
    Undefined symbols for architecture x86_64:
      "_ffi_closure_alloc", referenced from:
          _ctypes_make_function_pointer in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
      "_ffi_closure_free", referenced from:
          _finalize_closure in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
      "_ffi_prep_closure_loc", referenced from:
          _ctypes_make_function_pointer in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    File "caml_startup", line 1:
    Error: Error during linking
    error: command failed: 'dune' 'build' '-p' 'Revery' '-j4' (exited with 1)
```

**Comment by glennsl** [comment]
Maybe related to https://github.com/revery-ui/revery/issues/742?

**Comment by glennsl** [comment]
Can't reproduce on my MBP running Catalina, but the integration test fails mysteriously there.

**Comment by bryphe** [comment]
Hmm, that linker error doesn't seem related revery-ui/revery#742- that one is specific to `pkg-config` picking up the wrong `libjpeg`. These missing symbols are related to `libffi`.

One thing to rule out is a cache issue - perhaps try re-running after removing the 'restore-build-cache.yml` steps from both MacOS builds (hygiene checks and the 'real' build): https://github.com/onivim/oni2/blob/174af59f0c94303c2e6aec4a5b5e6292af16182f/azure-pipelines.yml#L34

And it looks like its failing building Revery - does Revery itself build with 4.08? Might be worth trying that on CI too, separately.

**Comment by glennsl** [comment]
> Hmm, that linker error doesn't seem related revery-ui/revery#742- that one is specific to pkg-config picking up the wrong libjpeg. These missing symbols are related to libffi.

They're both weird linker errors on macOS though. That's good enough for me to draw comparisons!

> One thing to rule out is a cache issue - perhaps try re-running after removing the 'restore-build-cache.yml` steps from both MacOS builds (hygiene checks and the 'real' build):

Good idea! Trying now.

> And it looks like its failing building Revery - does Revery itself build with 4.08? Might be worth trying that on CI too, separately.

For a period it was on 4.08, but that was of course before Skia. Will try that too.

**Comment by glennsl** [comment]
Hmm, Revery builds fine, while this fails with the same error even with cache disabled. Any other ideas?

**Comment by bryphe** [comment]
> Any other ideas? 

Unfortunately I don't have anything off the top of my head at the moment. The dependency comes from here: https://github.com/revery-ui/reason-skia/blob/03f05be7d2a86a9294ee4a02b86ecedf8a589124/package.json#L44

With the package.json here:
https://github.com/esy-ocaml/libffi/blob/esy/package.json

Sometimes the linker needs some help in the form of the `DYLD_LIBRARY_PATH` to resolve dependencies - it might be worth adding a `DYLD_LIBRARY_PATH` to the environment for `libffi` - like this one: https://github.com/revery-ui/libjpeg-turbo/blob/61e031fdd8d621cb183caaea07133bb346310892/package.json#L15

**Comment by glennsl** [comment]
> Sometimes the linker needs some help in the form of the DYLD_LIBRARY_PATH to resolve dependencies - it might be worth adding a DYLD_LIBRARY_PATH to the environment for libffi

To `esy-libffi`s `package.json` or to `oni2`'s?

**Comment by bryphe** [comment]
> To esy-libffis package.json or to oni2's?

Was thinking to `esy-libffi`. The other option would be to statically link `libffi`, but might require changing how it is linked in ctypes: https://github.com/ocamllabs/ocaml-ctypes/blob/e7063afab825982a3fb9b937ca1c5384ec26f4e4/src/discover/discover.ml

**Comment by glennsl** [comment]
Statically linking libffi fixed it! Adding the `LIBRARY_PATH` environnment variables did not.

Now we just need to get the upstream PRs merged, before updating the dependencies here and finally merging!

File: package.json [hunk 3]
```diff
@@ -249,12 +249,17 @@
     "esy-sdl2": "revery-ui/esy-sdl2#b63892b",
     "esy-skia": "revery-ui/esy-skia#91b10c9",
     "timber": "glennsl/timber#ae065bb",
-    "yarn-pkg-config": "esy-ocaml/yarn-pkg-config#db3a0b6"
+    "yarn-pkg-config": "esy-ocaml/yarn-pkg-config#db3a0b6",
+    "rench": "bryphe/rench#a976fe5",
+    "@esy-ocaml/reason": "facebook/reason#8f71db0",
+    "reason-textmate": "onivim/reason-textmate#5f0dc38",
+    "@esy-ocaml/libffi": "glennsl/libffi#0d21ddb",
+    "reason-skia": "glennsl/reason-skia#dd0bf60"
```
Comment (glennsl) [inline package.json]: TODO: Update these before merging.

**Comment by bryphe** [comment]
> Statically linking libffi fixed it! Adding the LIBRARY_PATH environnment variables did not.

Woohoo! 🎉 Thanks for testing those out.

It looked like we were blocked on this PR: https://github.com/esy-ocaml/libffi/pull/3 - went ahead and merged it. Hopefully that unblocks the rest of the downstream deps now.

**Comment by glennsl** [comment]
Can't actually build it locally because of https://github.com/revery-ui/reason-harfbuzz/pull/4, but hoping CI passes.

> It looked like we were blocked on this PR: esy-ocaml/libffi#3 - went ahead and merged 

Thanks! Didn't realize you had commit rights to that one too.

**Comment by glennsl** [comment]
> hoping CI passes

It did not :(

**Comment by bryphe** [comment]
> Thanks! Didn't realize you had commit rights to that one too.

I actually forgot I did... surprising to me too.

Looks like a few remaining spots that need to be tweaked, probably due to the Skia merge...
```
info esy build 0.6.1 (using package.json)
      ocamlc src/Core/.Oni_Core.objs/byte/oni_Core__ConfigurationParser.{cmo,cmt} (exit 2)
(cd D:/a/1/s/_esy/default/store/b/oni2-db8adc59\default && C:\Users\VssAdministrator\.esy\3______________________________________________________\i\ocaml-4.8.1000-a241290c\bin\ocamlc.opt.exe -w -40 -g -bin-annot -I src/Core/.Oni_Core.objs/byte -I C:/Users/VssAdministrator/.esy/3/i/brisk__s__brisk_reconciler-3c8dfb75/lib\brisk-reconciler -I C:/Users/VssAdministrator/.esy/3/i/editor_core_types-7595a562/lib\editor-core-types -I C:/Users/VssAdministrator/.esy/3/i/flex-1.2.2-9fd96bc8/lib\flex -I C:/Users/VssAdministrator/.esy/3/i/ocaml-4.8.1000-a241290c/lib/ocaml\threads -I C:/Users/VssAdministrator/.esy/3/i/opam__s__astring-opam__c__0.8.3-30e8a7bc/lib\astring -I C:/Users/VssAdministrator/.esy/3/i/opam__s__biniou-opam__c__1.2.0-834e6dd9/lib\biniou -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\default_config -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\dyn -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\lib_default -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\library -I C:/Users/VssAdministrator/.esy/3/i/opam__s__charinfo__width-opam__c__1.1.0-14cb3010/lib\charInfo_width -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ctypes-opam__c__0.15.1-70985e6d/lib\ctypes -I C:/Users/VssAdministrator/.esy/3/i/opam__s__decoders-opam__c__0.3.0-902aa8d5/lib\decoders -I C:/Users/VssAdministrator/.esy/3/i/opam__s__decoders_yojson-opam__c__0.3.0-a1446ae9/lib\decoders-yojson -I C:/Users/VssAdministrator/.esy/3/i/opam__s__easy_format-opam__c__1.3.1-9255575c/lib\easy-format -I C:/Users/VssAdministrator/.esy/3/i/opam__s__fmt-opam__c__0.8.8-6b723d0b/lib\fmt -I C:/Users/VssAdministrator/.esy/3/i/opam__s__fpath-opam__c__0.7.2-eb8a4b1e/lib\fpath -I C:/Users/VssAdministrator/.esy/3/i/opam__s__integers-opam__c__0.3.0-bd39a772/lib\integers -I C:/Users/VssAdministrator/.esy/3/i/opam__s__logs-opam__c__0.7.0-9e3913c2/lib\logs -I C:/Users/VssAdministrator/.esy/3/i/opam__s__lwt-opam__c__4.5.0-d7686d0b/lib\lwt -I C:/Users/VssAdministrator/.esy/3/i/opam__s__lwt-opam__c__4.5.0-d7686d0b/lib\lwt\unix -I C:/Users/VssAdministrator/.esy/3/i/opam__s__mmap-opam__c__1.1.0-994217a1/lib\mmap -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ocamlfind-opam__c__1.8.1-ff386450/lib\bytes -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ocplib_endian-opam__c__1.0-f1db3f08/lib\ocplib-endian -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ppx__deriving-opam__c__4.4-bcf947dc/lib\ppx_deriving\runtime -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ppx__deriving__yojson-opam__c__3.5.1-2c813648/lib\ppx_deriving_yojson\runtime -I C:/Users/VssAdministrator/.esy/3/i/opam__s__re-opam__c__1.9.0-d102bd7d/lib\re -I C:/Users/VssAdministrator/.esy/3/i/opam__s__react-opam__c__1.2.1-031cd1a4/lib\react -I C:/Users/VssAdministrator/.esy/3/i/opam__s__result-opam__c__1.4-38a3dec4/lib\result -I C:/Users/VssAdministrator/.esy/3/i/opam__s__seq-opam__c__base-9ba0910f/lib\seq -I C:/Users/VssAdministrator/.esy/3/i/opam__s__stdlib_shims-opam__c__0.1.0-3ca176d0/lib\stdlib-shims -I C:/Users/VssAdministrator/.esy/3/i/opam__s__yojson-49b10575/lib\yojson -I C:/Users/VssAdministrator/.esy/3/i/reason_font_manager-2.0.1-1645b510/lib\reason-font-manager -I C:/Users/VssAdministrator/.esy/3/i/reason_gl_matrix-0.9.9306-4cda2a1e/lib\reglm -I C:/Users/VssAdministrator/.esy/3/i/reason_harfbuzz-1.91.5003-77a24ce4/lib\harfbuzz -I C:/Users/VssAdministrator/.esy/3/i/reason_libvim-b8e20a18/lib\libvim -I C:/Users/VssAdministrator/.esy/3/i/reason_native__s__console-0.0.3-265481e3/lib\console\lib -I C:/Users/VssAdministrator/.esy/3/i/reason_oniguruma-6.94.1000-1542c9c3/lib\oniguruma -I C:/Users/VssAdministrator/.esy/3/i/reason_sdl2-2.10.3016-7e84fae4/lib\sdl2 -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/bindings -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/c -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/types -I C:/Users/VssAdministrator/.esy/3/i/reason_textmate-f14a357e/lib\textmate -I C:/Users/VssAdministrator/.esy/3/i/reasonfuzz-dea6ed90/lib\Matchers -I C:/Users/VssAdministrator/.esy/3/i/reasonfuzz-dea6ed90/lib\ReasonFuzz -I C:/Users/VssAdministrator/.esy/3/i/rebez-b29686b6/lib\rebez\lib -I C:/Users/VssAdministrator/.esy/3/i/rench-d10ef626/lib\Rench -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Core -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Draw -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Font -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Math -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Native -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Components -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Hooks -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Primitives -I C:/Users/VssAdministrator/.esy/3/i/revery_text_wrap-43dea086/lib\revery-text-wrap -I C:/Users/VssAdministrator/.esy/3/i/timber-00eaefb4/lib\timber -I src/Core/Kernel/.Kernel.objs/byte -I src/Core/Kernel/.Kernel.objs/native -I src/Core/Utility/.Utility.objs/byte -I src/Core/Utility/.Utility.objs/native -I vendor/zed/.zed_oni.objs/byte -I vendor/zed/.zed_oni.objs/native -intf-suffix .ml -no-alias-deps -open Oni_Core__ -o src/Core/.Oni_Core.objs/byte/oni_Core__ConfigurationParser.cmo -c -impl src/Core/ConfigurationParser.re.pp.ml)
# Unformatted Error Output:
# File "src/Core/ConfigurationParser.re", line 37, characters 18-30:
# Error: Unbound module OptionEx
# Hint: Did you mean Option?


 ERROR  src/Core/ConfigurationParser.re:37 18-30 

 34 ┆   let floatFromIntMaybe =
 35 ┆     int_of_string_opt(str) |> Option.map(float_of_int);
 36 ┆ 
 37 ┆   floatMaybe |> OptionEx.or_(floatFromIntMaybe) |> Option.value(~default);
 38 ┆ | _ => default
 39 ┆ };
 40 ┆ 

Module OptionEx; not found in included libraries.

Hint: did you mean Option?


    ocamlopt src/Core/.Oni_Core.objs/native/oni_Core__ConfigurationParser.{cmx,o} (exit 2)
(cd D:/a/1/s/_esy/default/store/b/oni2-db8adc59\default && C:\Users\VssAdministrator\.esy\3______________________________________________________\i\ocaml-4.8.1000-a241290c\bin\ocamlopt.opt.exe -w -40 -g -I src/Core/.Oni_Core.objs/byte -I src/Core/.Oni_Core.objs/native -I C:/Users/VssAdministrator/.esy/3/i/brisk__s__brisk_reconciler-3c8dfb75/lib\brisk-reconciler -I C:/Users/VssAdministrator/.esy/3/i/editor_core_types-7595a562/lib\editor-core-types -I C:/Users/VssAdministrator/.esy/3/i/flex-1.2.2-9fd96bc8/lib\flex -I C:/Users/VssAdministrator/.esy/3/i/ocaml-4.8.1000-a241290c/lib/ocaml\threads -I C:/Users/VssAdministrator/.esy/3/i/opam__s__astring-opam__c__0.8.3-30e8a7bc/lib\astring -I C:/Users/VssAdministrator/.esy/3/i/opam__s__biniou-opam__c__1.2.0-834e6dd9/lib\biniou -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\default_config -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\dyn -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\lib_default -I C:/Users/VssAdministrator/.esy/3/i/opam__s__camomile-opam__c__1.0.1-6ddcdcfe/lib\camomile\library -I C:/Users/VssAdministrator/.esy/3/i/opam__s__charinfo__width-opam__c__1.1.0-14cb3010/lib\charInfo_width -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ctypes-opam__c__0.15.1-70985e6d/lib\ctypes -I C:/Users/VssAdministrator/.esy/3/i/opam__s__decoders-opam__c__0.3.0-902aa8d5/lib\decoders -I C:/Users/VssAdministrator/.esy/3/i/opam__s__decoders_yojson-opam__c__0.3.0-a1446ae9/lib\decoders-yojson -I C:/Users/VssAdministrator/.esy/3/i/opam__s__easy_format-opam__c__1.3.1-9255575c/lib\easy-format -I C:/Users/VssAdministrator/.esy/3/i/opam__s__fmt-opam__c__0.8.8-6b723d0b/lib\fmt -I C:/Users/VssAdministrator/.esy/3/i/opam__s__fpath-opam__c__0.7.2-eb8a4b1e/lib\fpath -I C:/Users/VssAdministrator/.esy/3/i/opam__s__integers-opam__c__0.3.0-bd39a772/lib\integers -I C:/Users/VssAdministrator/.esy/3/i/opam__s__logs-opam__c__0.7.0-9e3913c2/lib\logs -I C:/Users/VssAdministrator/.esy/3/i/opam__s__lwt-opam__c__4.5.0-d7686d0b/lib\lwt -I C:/Users/VssAdministrator/.esy/3/i/opam__s__lwt-opam__c__4.5.0-d7686d0b/lib\lwt\unix -I C:/Users/VssAdministrator/.esy/3/i/opam__s__mmap-opam__c__1.1.0-994217a1/lib\mmap -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ocamlfind-opam__c__1.8.1-ff386450/lib\bytes -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ocplib_endian-opam__c__1.0-f1db3f08/lib\ocplib-endian -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ppx__deriving-opam__c__4.4-bcf947dc/lib\ppx_deriving\runtime -I C:/Users/VssAdministrator/.esy/3/i/opam__s__ppx__deriving__yojson-opam__c__3.5.1-2c813648/lib\ppx_deriving_yojson\runtime -I C:/Users/VssAdministrator/.esy/3/i/opam__s__re-opam__c__1.9.0-d102bd7d/lib\re -I C:/Users/VssAdministrator/.esy/3/i/opam__s__react-opam__c__1.2.1-031cd1a4/lib\react -I C:/Users/VssAdministrator/.esy/3/i/opam__s__result-opam__c__1.4-38a3dec4/lib\result -I C:/Users/VssAdministrator/.esy/3/i/opam__s__seq-opam__c__base-9ba0910f/lib\seq -I C:/Users/VssAdministrator/.esy/3/i/opam__s__stdlib_shims-opam__c__0.1.0-3ca176d0/lib\stdlib-shims -I C:/Users/VssAdministrator/.esy/3/i/opam__s__yojson-49b10575/lib\yojson -I C:/Users/VssAdministrator/.esy/3/i/reason_font_manager-2.0.1-1645b510/lib\reason-font-manager -I C:/Users/VssAdministrator/.esy/3/i/reason_gl_matrix-0.9.9306-4cda2a1e/lib\reglm -I C:/Users/VssAdministrator/.esy/3/i/reason_harfbuzz-1.91.5003-77a24ce4/lib\harfbuzz -I C:/Users/VssAdministrator/.esy/3/i/reason_libvim-b8e20a18/lib\libvim -I C:/Users/VssAdministrator/.esy/3/i/reason_native__s__console-0.0.3-265481e3/lib\console\lib -I C:/Users/VssAdministrator/.esy/3/i/reason_oniguruma-6.94.1000-1542c9c3/lib\oniguruma -I C:/Users/VssAdministrator/.esy/3/i/reason_sdl2-2.10.3016-7e84fae4/lib\sdl2 -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/bindings -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/c -I C:/Users/VssAdministrator/.esy/3/i/reason_skia-ca38abc6/lib\skia\wrapped/types -I C:/Users/VssAdministrator/.esy/3/i/reason_textmate-f14a357e/lib\textmate -I C:/Users/VssAdministrator/.esy/3/i/reasonfuzz-dea6ed90/lib\Matchers -I C:/Users/VssAdministrator/.esy/3/i/reasonfuzz-dea6ed90/lib\ReasonFuzz -I C:/Users/VssAdministrator/.esy/3/i/rebez-b29686b6/lib\rebez\lib -I C:/Users/VssAdministrator/.esy/3/i/rench-d10ef626/lib\Rench -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Core -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Draw -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Font -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Math -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\Native -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Components -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Hooks -I C:/Users/VssAdministrator/.esy/3/i/revery-27715e0b/lib\Revery\UI_Primitives -I C:/Users/VssAdministrator/.esy/3/i/revery_text_wrap-43dea086/lib\revery-text-wrap -I C:/Users/VssAdministrator/.esy/3/i/timber-00eaefb4/lib\timber -I src/Core/Kernel/.Kernel.objs/byte -I src/Core/Kernel/.Kernel.objs/native -I src/Core/Utility/.Utility.objs/byte -I src/Core/Utility/.Utility.objs/native -I vendor/zed/.zed_oni.objs/byte -I vendor/zed/.zed_oni.objs/native -intf-suffix .ml -no-alias-deps -open Oni_Core__ -o src/Core/.Oni_Core.objs/native/oni_Core__ConfigurationParser.cmx -c -impl src/Core/ConfigurationParser.re.pp.ml)
# Unformatted Error Output:
# File "src/Core/ConfigurationParser.re", line 37, characters 18-30:
# Error: Unbound module OptionEx
# Hint: Did you mean Option?


 ERROR  src/Core/ConfigurationParser.re:37 18-30 

 34 ┆   let floatFromIntMaybe =
```

**Comment by glennsl** [comment]
Woo! It's in! FINALLY!
